import { SubclassFeature } from './subclassFeatures';

export interface MartialArtsAbility {
  id: string;
  name: string;
  description: string;
}

export const MARTIAL_ARTS_ABILITIES: MartialArtsAbility[] = [
  {
    id: "airshift",
    name: "Airshift",
    description: "You cannot be Grappled while conscious. While moving, you may travel across all terrain as difficult ground, ignoring all effects (e.g., walls/ ceilings, water, treetops, lava, spikes, clouds).",
  },
  {
    id: "blur",
    name: "Blur",
    description: "(1/encounter) When you Defend, you may first move up to half your speed away, taking no damage if you can out of range or have Full Cover.",
  },
  {
    id: "bodily_discipline",
    name: "Bodily Discipline",
    description: "You may spend 1 action to end any Wound condition.",
  },
  {
    id: "enduring_soul",
    name: "Enduring Soul",
    description: "Each time you roll Initiative, gain +LVL temp HP usable only on your first turn. These Hit Dice expire at the end of combat if unused.",
  },
  {
    id: "i_jump_on_his_back",
    name: "I Jump On His Back!",
    description: "While moving with your Windstep, if you move into the space of a creature your size or larger, you remain on top of its back. While on a creature this way, gain advantage on melee attacks against it, and any damage you avoid is dealt to it instead.",
  },
  {
    id: "kinetic_barrage",
    name: "Kinetic Barrage",
    description: "Whenever you miss an attack, gain a cumulative +STR Bonus to all damage you do for the rest of this encounter (a disciplined martial artist does not miss on purpose).",
  },
  {
    id: "mighty_soul",
    name: "Mighty Soul",
    description: "You cannot be moved against your will. Whenever you would fail a saving throw, you may gain a Wound in order to add your STR to the result you rolled. You may repeat this any number of times.",
  },
  {
    id: "quickstrike",
    name: "Quickstrike",
    description: "When you Interpose, you may first make one unarmed strike against the enemy for free.",
  },
  {
    id: "use_momentum",
    name: "Use Momentum",
    description: "Whenever you avoid all of the damage of a melee attack (whether it misses or you Defend), you may swap places with the attacker and then choose another target that is now within your attack's reach, and they are hit instead.",
  },
  {
    id: "vital_rejuvenation",
    name: "Vital Rejuvenation",
    description: "When you receive healing for the first time on a turn, you heal another target within 6 spaces HP equal to your STR.",
  },
  {
    id: "windstrider",
    name: "Windstrider",
    description: "If you move through the space of a willing creature while using Windstep, they can move with you and choose any space adjacent to your path of movement to end in.",
  },
];

export const ZEPHYR_CLASS_FEATURES = [
  {
    id: "zephyr_iron_defense",
    name: "Iron Defense",
    level: 1,
    description: "Your armor equals DEX+STR as long as you are unarmored.",
    requires_choice: false,
  },
  {
    id: "zephyr_swift_fists",
    name: "Swift Fists",
    level: 1,
    description: "Your unarmed strikes are not subject to disadvantage imposed by Rushed Attacks (see pg. 13 of the Core Rules), and their damage is 1d4+STR.",
    requires_choice: false,
  },
  {
    id: "zephyr_swift_feet",
    name: "Swift Feet",
    level: 2,
    description: "While unarmored, gain +2 speed and +LVL Initiative.\n\nBurst of Speed. When you roll Initiative, gain DEX Bursts of Speed to use during that encounter. (1/turn) You may spend 1 Burst of Speed to use any of the following maneuvers for free:\n• Sidestep. Defend, and the attack misses.\n• Whirling Defense. Defend and apply your armor to every attack this round.\n• Swiftstrike. Attack on your turn, and ignore disadvantage from Rushed Attacks.\n• Windstep. Move on your turn, ignoring difficult terrain.",
    requires_choice: false,
  },
  {
    id: "zephyr_subclass",
    name: "Subclass",
    level: 3,
    description: "Choose a Zephyr subclass.",
    requires_choice: true,
    choice_type: "single" as const,
    options: [
      { id: "pain", name: "Way of Pain" },
      { id: "flame", name: "Way of Flame" },
    ],
  },
  {
    id: "zephyr_kinetic_momentum",
    name: "Kinetic Momentum",
    level: 3,
    description: "Whenever you gain a Wound, gain a Burst of Speed.",
    requires_choice: false,
  },
  {
    id: "zephyr_ethereal_projection",
    name: "Ethereal Projection",
    level: 3,
    description: "(1/day) By meditating for at least 10 minutes, you can project an ethereal version of yourself up to 30 ft. away, passing through solid objects or barriers. You see through your projection's eyes, and it is visible to other creatures as a translucent vision of yourself. It cannot interact physically with the world (except to move freely) within a distance limit and lasts for up to 10 minutes.",
    requires_choice: false,
  },
  {
    id: "zephyr_unyielding_resolve",
    name: "Unyielding Resolve",
    level: 4,
    description: "Ignore the first Wound you would suffer each encounter (when-Wounded abilities, such as Kinetic Momentum, still trigger).",
    requires_choice: false,
  },
  {
    id: "zephyr_key_stat_increase_4",
    name: "Key Stat Increase",
    level: 4,
    description: "+1 DEX or STR.",
    requires_choice: false,
  },
  {
    id: "zephyr_martial_master",
    name: "Martial Master",
    level: 4,
    description: "Choose a Martial Arts ability.",
    requires_choice: true,
    choice_type: "single" as const,
    options: MARTIAL_ARTS_ABILITIES.map(a => ({ id: a.id, name: a.name, text: a.description })),
  },
  {
    id: "zephyr_reverberating_strikes",
    name: "Reverberating Strikes",
    level: 5,
    description: "You learn to focus your energy and transfer it as an additional concussive force into your foes. Add LVL bludgeoning damage to all of your melee attacks.",
    requires_choice: false,
  },
  {
    id: "zephyr_secondary_stat_increase_5",
    name: "Secondary Stat Increase",
    level: 5,
    description: "+1 INT or WIL.",
    requires_choice: false,
  },
  {
    id: "zephyr_martial_master_2",
    name: "Martial Master (2)",
    level: 6,
    description: "Choose a 2nd Martial Arts Ability.",
    requires_choice: true,
    choice_type: "single" as const,
    options: MARTIAL_ARTS_ABILITIES.map(a => ({ id: a.id, name: a.name, text: a.description })),
  },
  {
    id: "zephyr_infuse_strength",
    name: "Infuse Strength",
    level: 6,
    description: "Action: Make an unarmed strike against an ally and infuse them with a portion of your own strength instead of harming them. Expend any number of Hit Dice and heal them as you would heal yourself during a Field Rest (roll them and add your STR to each).",
    requires_choice: false,
  },
  {
    id: "zephyr_subclass_7",
    name: "Subclass",
    level: 7,
    description: "Gain your Zephyr subclass feature.",
    requires_choice: false,
  },
  {
    id: "zephyr_martial_master_3",
    name: "Martial Master (3)",
    level: 8,
    description: "Choose a 3rd Martial Arts Ability.",
    requires_choice: true,
    choice_type: "single" as const,
    options: MARTIAL_ARTS_ABILITIES.map(a => ({ id: a.id, name: a.name, text: a.description })),
  },
  {
    id: "zephyr_key_stat_increase_8",
    name: "Key Stat Increase",
    level: 8,
    description: "+1 DEX or STR.",
    requires_choice: false,
  },
  {
    id: "zephyr_swift_feet_2",
    name: "Swift Feet (2)",
    level: 9,
    description: "Gain an additional +2 speed as long as you are unarmored.",
    requires_choice: false,
  },
  {
    id: "zephyr_secondary_stat_increase_9",
    name: "Secondary Stat Increase",
    level: 9,
    description: "+1 INT or WIL.",
    requires_choice: false,
  },
  {
    id: "zephyr_martial_master_4",
    name: "Martial Master (4)",
    level: 10,
    description: "Choose a 4th Martial Arts Ability.",
    requires_choice: true,
    choice_type: "single" as const,
    options: MARTIAL_ARTS_ABILITIES.map(a => ({ id: a.id, name: a.name, text: a.description })),
  },
  {
    id: "zephyr_unyielding_resolve_2",
    name: "Unyielding Resolve (2)",
    level: 10,
    description: "Ignore the first 2 Wounds you would suffer each encounter.",
    requires_choice: false,
  },
  {
    id: "zephyr_subclass_11",
    name: "Subclass",
    level: 11,
    description: "Gain your Zephyr subclass feature.",
    requires_choice: false,
  },
  {
    id: "zephyr_martial_master_5",
    name: "Martial Master (5)",
    level: 12,
    description: "Choose a 5th Martial Arts Ability.",
    requires_choice: true,
    choice_type: "single" as const,
    options: MARTIAL_ARTS_ABILITIES.map(a => ({ id: a.id, name: a.name, text: a.description })),
  },
  {
    id: "zephyr_key_stat_increase_12",
    name: "Key Stat Increase",
    level: 12,
    description: "+1 DEX or STR.",
    requires_choice: false,
  },
  {
    id: "zephyr_iron_defense_2",
    name: "Iron Defense (2)",
    level: 13,
    description: "Your armor is doubled while unarmored.",
    requires_choice: false,
  },
  {
    id: "zephyr_secondary_stat_increase_13",
    name: "Secondary Stat Increase",
    level: 13,
    description: "+1 INT or WIL.",
    requires_choice: false,
  },
  {
    id: "zephyr_martial_master_6",
    name: "Martial Master (6)",
    level: 14,
    description: "Choose a 6th Martial Arts Ability.",
    requires_choice: true,
    choice_type: "single" as const,
    options: MARTIAL_ARTS_ABILITIES.map(a => ({ id: a.id, name: a.name, text: a.description })),
  },
  {
    id: "zephyr_subclass_15",
    name: "Subclass",
    level: 15,
    description: "Gain your Zephyr subclass feature.",
    requires_choice: false,
  },
  {
    id: "zephyr_martial_master_7",
    name: "Martial Master (7)",
    level: 16,
    description: "Choose a 7th Martial Arts Ability.",
    requires_choice: true,
    choice_type: "single" as const,
    options: MARTIAL_ARTS_ABILITIES.map(a => ({ id: a.id, name: a.name, text: a.description })),
  },
  {
    id: "zephyr_key_stat_increase_16",
    name: "Key Stat Increase",
    level: 16,
    description: "+1 DEX or STR.",
    requires_choice: false,
  },
  {
    id: "zephyr_unyielding_resolve_3",
    name: "Unyielding Resolve (3)",
    level: 17,
    description: "Ignore the first 3 Wounds you would suffer each encounter. You have advantage on STR saves while Dying.",
    requires_choice: false,
  },
  {
    id: "zephyr_secondary_stat_increase_17",
    name: "Secondary Stat Increase",
    level: 17,
    description: "+1 INT or WIL.",
    requires_choice: false,
  },
  {
    id: "zephyr_martial_master_8",
    name: "Martial Master (8)",
    level: 18,
    description: "Choose an 8th Martial Arts Ability.",
    requires_choice: true,
    choice_type: "single" as const,
    options: MARTIAL_ARTS_ABILITIES.map(a => ({ id: a.id, name: a.name, text: a.description })),
  },
  {
    id: "zephyr_epic_boon",
    name: "Epic Boon",
    level: 19,
    description: "Choose an Epic Boon (see pg. 23 of the GM's Guide).",
    requires_choice: false,
  },
  {
    id: "zephyr_windborne",
    name: "Windborne",
    level: 20,
    description: "+1 to any 2 of your stats. +1 additional burst of speed when you roll Initiative. Permanently gain 1 action (while Dying, you have a max of 2 actions).",
    requires_choice: false,
  },
];

export const PAIN_SUBCLASS_FEATURES: SubclassFeature[] = [
  {
    id: "pain_bring_the_pain",
    name: "Bring the Pain",
    level: 3,
    subclassId: "pain",
    subclassName: "Way of Pain",
    description: "(1/round) You may turn any melee attack against you into a crit. Whenever you are crit, reduce the damage by half. The attacker takes the same amount of damage you took (ignoring armor). You may suffer 1 Wound to double the damage the enemy takes.",
  },
  {
    id: "pain_share_my_pain",
    name: "Share My Pain",
    level: 7,
    subclassId: "pain",
    subclassName: "Way of Pain",
    description: "Your Swiftstrike can also target a 2nd creature within Reach 2.",
  },
  {
    id: "pain_sharpens_the_mind",
    name: "Pain Sharpens the Mind",
    level: 11,
    subclassId: "pain",
    subclassName: "Way of Pain",
    description: "While you are Bloodied, gain advantage on the first attack you make each turn, and on all saves.",
  },
  {
    id: "pain_echoed_agony",
    name: "Echoed Agony",
    level: 15,
    subclassId: "pain",
    subclassName: "Way of Pain",
    description: "Your Swiftstrike can also target a 3rd creature within Reach 4.",
  },
];

export const FLAME_SUBCLASS_FEATURES: SubclassFeature[] = [
  {
    id: "flame_exploding_soul",
    name: "Exploding Soul",
    level: 3,
    subclassId: "flame",
    subclassName: "Way of Flame",
    description: "(1/round) On your turn, you may suffer a Wound. Whenever you gain a Wound, deal STR+LVL Wounds damage to any creatures you choose within 2 spaces (ignoring armor) and give them the Smoldering condition.",
  },
  {
    id: "flame_blazing_speed",
    name: "Blazing Speed",
    level: 7,
    subclassId: "flame",
    subclassName: "Way of Flame",
    description: "Gain +2 speed while using Windstep. After you cease movement with Windstep, enemies you passed through take STR+DEX fire damage. You may have Smoldering enemies take double, ending the condition.",
  },
  {
    id: "flame_chain_reaction",
    name: "Chain Reaction",
    level: 11,
    subclassId: "flame",
    subclassName: "Way of Flame",
    description: "(1/turn) When you crit, deal fire damage equal to your STR+Wounds to creatures of your choice within 2 spaces of your target. Repeat any number of times, targeting creatures not yet damaged by this effect within 2 spaces of any already damaged.",
  },
  {
    id: "flame_burning_soul",
    name: "Burning Soul",
    level: 15,
    subclassId: "flame",
    subclassName: "Way of Flame",
    description: "Double any fire damage you deal.",
  },
];

export const ZEPHYR_SUBCLASS_FEATURES = [
  ...PAIN_SUBCLASS_FEATURES,
  ...FLAME_SUBCLASS_FEATURES,
];
